language: node_js

node_js:
  - stable

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - npm test

branches:
  only:
    - master

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change
